on:
  push:
    tags:
      - v*

env:
  NODE_VERSION: '12.x'
  PUB_PATH: '/pwa-pingshui/'

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    #- uses: actions/cache@v1
    #  id: cache
    #  with:
    #    path: node_modules
    #    key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
    #    restore-keys: |
    #      ${{ runner.os }}-node-
    - name: Install Packages
      uses: borales/actions-yarn@v2.0.0
      with:
          cmd: install
    - name: Build App
      uses: borales/actions-yarn@v2.0.0
      with:
          cmd: build
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
